# Site
repository: Erinliutr/ErinLiutr.github.io
favicon: images/favicon.ico

# Personal info
name: Erin (Tianrui) Liu
title: Undergraduate developer & researcher
email: tl62@rice.edu
website: www.github.com/Erinliutr/ErinLiutr.github.io

# dark mode
darkmode: false

github_username:  ErinLiutr
linkedin_username: erinliutr

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Erin and I'm a junior at Rice University, majoring Computer Science and Mathematics.
  #  <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
